const LANGS = {
  en:{
    nav:{home:"Home", membership:"Membership", login:"Login", signup:"Sign Up"},
    h1:"Luxury stays.<br><span class='gold'>Global reach.</span>",
    pay:"Cards, bank transfer & crypto (BTC · ETH · USDT).",
    filters:"Filters", search:"Search", placeholder:"Paris, Tokyo, Istanbul…",
    card1:"Verified stays", card1sub:"Top picks near you.",
    card2:"StayWorld+ Rewards", card2sub:"Earn points on every booking.",
    card3:"Secure payments", card3sub:"Visa, Mastercard, Amex & Crypto.",
    membership:{
      title:"Membership Benefits",
      subtitle:"Higher tiers include all perks from lower tiers.",
      levels:{bronze:"Bronze",silver:"Silver",gold:"Gold",platinum:"Platinum",diamond:"Diamond",elite:"Elite"},
      perks:{ points_back:"{percent}% points back on each booking" },
      retention_rule:"If there’s no booking for {days} days, you’ll be auto-downgraded by 1 level.",
      progress_title:"Top tier achieved.",
      progress_to_next:"Only {amount} left to reach {level}.",
      status_current_level:"Your level: {level}",
      member_prices:"Member-only prices",
      basic_support:"Standard support",
      secure_pay:"Secure payments (Cards & Crypto)",
      free_cancel:"Free-cancel window",
      priority_email:"Priority email support",
      priority_chat:"Priority live chat",
      late_checkout:"Late checkout (when available)",
      upgrade_when_available:"Room upgrade (when available)",
      b2b_invoice:"B2B invoice support",
      elite_concierge:"Elite concierge access",
      defaults:{days:60}
    }
  },
  ko:{
    nav:{home:"홈", membership:"멤버십", login:"로그인", signup:"가입"},
    h1:"럭셔리 스테이.<br><span class='gold'>글로벌 리치.</span>",
    pay:"카드, 계좌이체 & 크립토 (BTC · ETH · USDT).",
    filters:"필터", search:"검색", placeholder:"파리, 도쿄, 이스탄불…",
    card1:"인증 숙소", card1sub:"가까운 베스트 픽.",
    card2:"StayWorld+ 리워드", card2sub:"매 예약마다 포인트 적립.",
    card3:"안전한 결제", card3sub:"Visa, Mastercard, Amex & 크립토.",
    membership:{
      title:"멤버십 혜택",
      subtitle:"상위 등급은 하위 등급 혜택을 모두 포함합니다.",
      levels:{bronze:"브론즈",silver:"실버",gold:"골드",platinum:"플래티넘",diamond:"다이아몬드",elite:"엘리트"},
      perks:{ points_back:"예약 시 {percent}% 포인트 적립" },
      retention_rule:"예약이 {days}일 이상 없으면 자동으로 1단계 강등됩니다.",
      progress_title:"최상위 등급에 도달했습니다.",
      progress_to_next:"{level}까지 {amount} 남았습니다.",
      status_current_level:"현재 레벨: {level}",
      member_prices:"멤버 전용 가격",
      basic_support:"기본 고객 지원",
      secure_pay:"안전한 결제(카드 & 크립토)",
      free_cancel:"무료 취소 기간",
      priority_email:"우선 이메일 지원",
      priority_chat:"우선 실시간 채팅",
      late_checkout:"레이트 체크아웃(가능 시)",
      upgrade_when_available:"객실 업그레이드(가능 시)",
      b2b_invoice:"기업용 계산서 지원",
      elite_concierge:"엘리트 컨시어지",
      defaults:{days:60}
    }
  },
  fr:{
    nav:{home:"Accueil", membership:"Adhésion", login:"Connexion", signup:"S’inscrire"},
    h1:"Séjours de luxe.<br><span class='gold'>Portée mondiale.</span>",
    pay:"Cartes, virement & crypto (BTC · ETH · USDT).",
    filters:"Filtres", search:"Rechercher", placeholder:"Paris, Tokyo, Istanbul…",
    card1:"Séjours vérifiés", card1sub:"Meilleures options près de chez vous.",
    card2:"Récompenses StayWorld+", card2sub:"Des points à chaque réservation.",
    card3:"Paiements sécurisés", card3sub:"Visa, Mastercard, Amex & Crypto.",
    membership:{
      title:"Avantages du programme",
      subtitle:"Les niveaux supérieurs incluent tous les avantages des niveaux inférieurs.",
      levels:{bronze:"Bronze",silver:"Argent",gold:"Or",platinum:"Platine",diamond:"Diamant",elite:"Élite"},
      perks:{ points_back:"{percent}% de points à chaque réservation" },
      retention_rule:"Sans réservation pendant {days} jours, rétrogradation automatique d’un niveau.",
      progress_title:"Niveau maximal atteint.",
      progress_to_next:"Plus que {amount} pour atteindre {level}.",
      status_current_level:"Votre niveau : {level}",
      member_prices:"Tarifs réservés aux membres",
      basic_support:"Assistance standard",
      secure_pay:"Paiements sécurisés (Cartes & Crypto)",
      free_cancel:"Fenêtre d’annulation gratuite",
      priority_email:"Assistance e-mail prioritaire",
      priority_chat:"Chat prioritaire",
      late_checkout:"Départ tardif (si disponible)",
      upgrade_when_available:"Surclassement (si disponible)",
      b2b_invoice:"Facturation B2B",
      elite_concierge:"Conciergerie Élite",
      defaults:{days:60}
    }
  },
  ja:{
    nav:{home:"ホーム", membership:"メンバーシップ", login:"ログイン", signup:"登録"},
    h1:"ラグジュアリーな滞在。<br><span class='gold'>グローバルに。</span>",
    pay:"カード・振込・暗号資産 (BTC · ETH · USDT)。",
    filters:"フィルター", search:"検索", placeholder:"パリ、東京、イスタンブール…",
    card1:"認証済みステイ", card1sub:"近くのおすすめ。",
    card2:"StayWorld+ リワード", card2sub:"予約ごとにポイント獲得。",
    card3:"安全な支払い", card3sub:"Visa・Mastercard・Amex・暗号資産。",
    membership:{
      title:"メンバーシップ特典",
      subtitle:"上位ランクは下位ランクの特典をすべて含みます。",
      levels:{bronze:"ブロンズ",silver:"シルバー",gold:"ゴールド",platinum:"プラチナ",diamond:"ダイヤモンド",elite:"エリート"},
      perks:{ points_back:"予約ごとに{percent}%ポイント還元" },
      retention_rule:"{days}日間予約がない場合、自動的に1ランク降格します。",
      progress_title:"最上位ランクに到達しました。",
      progress_to_next:"{level}まであと{amount}。",
      status_current_level:"現在のランク：{level}",
      member_prices:"会員限定価格",
      basic_support:"標準サポート",
      secure_pay:"安全な支払い（カード・暗号資産）",
      free_cancel:"無料キャンセル期間",
      priority_email:"優先メールサポート",
      priority_chat:"優先チャット",
      late_checkout:"レイトチェックアウト（空室時）",
      upgrade_when_available:"お部屋のアップグレード（空室時）",
      b2b_invoice:"B2B 請求書",
      elite_concierge:"エリート・コンシェルジュ",
      defaults:{days:60}
    }
  },
  de:{
    nav:{home:"Start", membership:"Mitgliedschaft", login:"Anmelden", signup:"Registrieren"},
    h1:"Luxuriöse Aufenthalte.<br><span class='gold'>Weltweite Reichweite.</span>",
    pay:"Karten, Überweisung & Krypto (BTC · ETH · USDT).",
    filters:"Filter", search:"Suchen", placeholder:"Paris, Tokio, Istanbul…",
    card1:"Verifizierte Unterkünfte", card1sub:"Top-Empfehlungen in deiner Nähe.",
    card2:"StayWorld+ Prämien", card2sub:"Punkte bei jeder Buchung.",
    card3:"Sichere Zahlungen", card3sub:"Visa, Mastercard, Amex & Krypto.",
    membership:{
      title:"Mitgliedschaftsvorteile",
      subtitle:"Höhere Stufen enthalten alle Vorteile der unteren Stufen.",
      levels:{bronze:"Bronze",silver:"Silber",gold:"Gold",platinum:"Platin",diamond:"Diamant",elite:"Elite"},
      perks:{ points_back:"{percent}% Punkte pro Buchung" },
      retention_rule:"Ohne Buchung innerhalb von {days} Tagen automatische Herabstufung um eine Stufe.",
      progress_title:"Höchste Stufe erreicht.",
      progress_to_next:"Nur noch {amount} bis {level}.",
      status_current_level:"Dein Level: {level}",
      member_prices:"Mitgliederpreise",
      basic_support:"Standard-Support",
      secure_pay:"Sichere Zahlungen (Karten & Krypto)",
      free_cancel:"Kostenlose Stornofrist",
      priority_email:"Priorisierter E-Mail-Support",
      priority_chat:"Priorisierter Chat",
      late_checkout:"Später Check-out (wenn verfügbar)",
      upgrade_when_available:"Upgrade (wenn verfügbar)",
      b2b_invoice:"B2B-Rechnungen",
      elite_concierge:"Elite-Concierge",
      defaults:{days:60}
    }
  },
  es:{ /* ... 같은 방식으로 추가 */ },
  it:{ /* ... 같은 방식으로 추가 */ },
  tr:{ /* ... 같은 방식으로 추가 */ },
  zh:{ /* ... 같은 방식으로 추가 */ },
  ru:{ /* ... 같은 방식으로 추가 */ }
};
