// StayWorld i18n — EN/KO/FR/TR/JA/DE/ES/IT/ZH/RU
(function(){
  const LANGS = {
    en:{ // NAV + INDEX
      nav:{home:"Home",deals:"Deals",membership:"Membership",host:"Host",support:"Support"},
      kicker:"Global stays • Verified hosts • Premium design",
      h1:"Luxury stays.<br><span class='gold'>Global reach.</span>",
      pay:"Cards, bank transfer & crypto (BTC · ETH · USDT).",
      filters:"Filters", search:"Search", popular:"Popular:", level:"Level", plus:"StayWorld+ active",
      deals_title:"Verified stays for you",
      level_hint:"Earn points. 60+ days inactive ➝ auto downgrade (−1 level).",
      placeholder:"Paris, Tokyo, Istanbul…",
      auth:{login:"Log in",signup:"Sign up"},

      // MEMBERSHIP
      membership_title:"StayWorld+ Rewards",
      membership_sub:"Higher levels include all benefits of lower levels.",
      level_bronze:"Bronze", bronze_desc:"Basic access granted upon signup.",
      level_silver:"Silver", silver_desc:"3% points on first booking.",
      level_gold:"Gold", gold_desc:"5% points on every booking + priority support.",
      level_platinum:"Platinum", platinum_desc:"7% points + seasonal discounts.",
      level_diamond:"Diamond", diamond_desc:"10% points + exclusive coupons + VIP support.",
      level_elite:"Elite", elite_desc:"15% points + private deals + urgent priority service.",

      // LOGIN
      login_title:"Log in to StayWorld", login_sub:"Welcome back. Access your bookings, points and perks.",
      login_email_label:"Email", login_email_ph:"you@example.com",
      login_password_label:"Password", login_password_ph:"Enter your password",
      login_remember:"Remember me", login_forgot:"Forgot password?", login_btn:"Log in",
      login_to_signup:"No account? Sign up",

      // SIGNUP
      signup_title:"Create your account", signup_sub:"Earn points from day one and unlock rewards.",
      signup_name_label:"Full name", signup_name_ph:"Your name",
      signup_email_label:"Email", signup_email_ph:"you@example.com",
      signup_password_label:"Password", signup_password_ph:"Minimum 8 characters",
      signup_btn:"Sign up", signup_to_login:"Already have an account? Log in",

      // HOST REGISTER
      host_title:"Host with confidence", host_sub:"ID verification required. Listings go live automatically.",
      host_benefits_title:"Benefits",
      host_benefit1:"Instant listing activation",
      host_benefit2:"Secure payments",
      host_benefit3:"AI-powered pricing tips",
      host_benefit4:"24/7 host support",
      host_verify_btn:"Start verification",
      host_register_title:"Register property",
      host_label_title:"Property title",
      host_label_city:"City",
      host_label_type:"Type",
      host_register_btn:"Submit registration"
    },
    ko:{
      nav:{home:"Home",deals:"딜",membership:"멤버십",host:"호스트",support:"지원"},
      kicker:"글로벌 스테이 • 인증된 호스트 • 프리미엄 디자인",
      h1:"럭셔리 스테이.<br><span class='gold'>글로벌 리치.</span>",
      pay:"카드, 계좌이체 & 크립토 (BTC · ETH · USDT).",
      filters:"필터", search:"검색", popular:"인기:", level:"레벨", plus:"StayWorld+ 활성",
      deals_title:"추천 인증 숙소",
      level_hint:"포인트 적립. 60일 이상 미접속 시 자동 강등(−1레벨).",
      placeholder:"파리, 도쿄, 이스탄불…",
      auth:{login:"로그인",signup:"가입"},

      membership_title:"StayWorld+ 리워드",
      membership_sub:"상위 등급은 하위 등급의 모든 혜택을 포함합니다.",
      level_bronze:"브론즈", bronze_desc:"회원가입 시 기본 부여.",
      level_silver:"실버", silver_desc:"첫 예약 시 3% 포인트 적립.",
      level_gold:"골드", gold_desc:"매 예약 5% 적립 + 우선 응대.",
      level_platinum:"플래티넘", platinum_desc:"7% 적립 + 시즌 할인.",
      level_diamond:"다이아몬드", diamond_desc:"10% 적립 + 전용 쿠폰 + VIP 지원.",
      level_elite:"엘리트", elite_desc:"15% 적립 + 프라이빗 딜 + 긴급 우선 처리.",

      login_title:"StayWorld 로그인", login_sub:"다시 오신 걸 환영합니다. 예약·포인트·혜택을 확인하세요.",
      login_email_label:"이메일", login_email_ph:"you@example.com",
      login_password_label:"비밀번호", login_password_ph:"비밀번호를 입력하세요",
      login_remember:"자동 로그인", login_forgot:"비밀번호 찾기", login_btn:"로그인",
      login_to_signup:"계정이 없나요? 가입하기",

      signup_title:"계정 만들기", signup_sub:"첫날부터 포인트 적립, 리워드 해제.",
      signup_name_label:"이름", signup_name_ph:"이름을 입력",
      signup_email_label:"이메일", signup_email_ph:"you@example.com",
      signup_password_label:"비밀번호", signup_password_ph:"최소 8자",
      signup_btn:"가입", signup_to_login:"이미 계정이 있나요? 로그인",

      host_title:"신뢰할 수 있는 호스팅",
      host_sub:"신원 인증 필요. 등록 즉시 자동 게재.",
      host_benefits_title:"혜택",
      host_benefit1:"즉시 게재",
      host_benefit2:"안전한 결제",
      host_benefit3:"AI 요금 제안",
      host_benefit4:"24/7 호스트 지원",
      host_verify_btn:"인증 시작",
      host_register_title:"숙소 등록",
      host_label_title:"숙소 제목",
      host_label_city:"도시",
      host_label_type:"유형",
      host_register_btn:"등록 제출"
    },
    fr:{
      nav:{home:"Accueil",deals:"Offres",membership:"Adhésion",host:"Hôte",support:"Assistance"},
      kicker:"Séjours mondiaux • Hôtes vérifiés • Design premium",
      h1:"Séjours de luxe.<br><span class='gold'>Portée mondiale.</span>",
      pay:"Cartes, virement & crypto (BTC · ETH · USDT).",
      filters:"Filtres", search:"Rechercher", popular:"Populaire :", level:"Niveau", plus:"StayWorld+ actif",
      deals_title:"Séjours vérifiés pour vous",
      level_hint:"Gagnez des points. 60+ jours inactif ➝ rétrogradation (−1).",
      placeholder:"Paris, Tokyo, Istanbul…",
      auth:{login:"Connexion",signup:"S’inscrire"},

      membership_title:"Récompenses StayWorld+",
      membership_sub:"Les niveaux supérieurs incluent tous les avantages des niveaux inférieurs.",
      level_bronze:"Bronze", bronze_desc:"Accès de base à l’inscription.",
      level_silver:"Argent", silver_desc:"3% de points à la première réservation.",
      level_gold:"Or", gold_desc:"5% de points par réservation + support prioritaire.",
      level_platinum:"Platine", platinum_desc:"7% de points + réductions saisonnières.",
      level_diamond:"Diamant", diamond_desc:"10% de points + coupons exclusifs + support VIP.",
      level_elite:"Élite", elite_desc:"15% de points + offres privées + service urgent prioritaire.",

      login_title:"Connexion à StayWorld", login_sub:"Ravi de vous revoir. Accédez à vos réservations, points et avantages.",
      login_email_label:"E-mail", login_email_ph:"vous@exemple.com",
      login_password_label:"Mot de passe", login_password_ph:"Entrez votre mot de passe",
      login_remember:"Se souvenir de moi", login_forgot:"Mot de passe oublié ?", login_btn:"Se connecter",
      login_to_signup:"Pas de compte ? Inscrivez-vous",

      signup_title:"Créez votre compte", signup_sub:"Gagnez des points dès le premier jour.",
      signup_name_label:"Nom complet", signup_name_ph:"Votre nom",
      signup_email_label:"E-mail", signup_email_ph:"vous@exemple.com",
      signup_password_label:"Mot de passe", signup_password_ph:"Au moins 8 caractères",
      signup_btn:"S’inscrire", signup_to_login:"Vous avez déjà un compte ? Connectez-vous",

      host_title:"Hébergez en toute confiance", host_sub:"Vérification d’identité requise. Mise en ligne automatique.",
      host_benefits_title:"Avantages",
      host_benefit1:"Activation instantanée",
      host_benefit2:"Paiements sécurisés",
      host_benefit3:"Conseils tarifaires par IA",
      host_benefit4:"Support hôte 24/7",
      host_verify_btn:"Démarrer la vérification",
      host_register_title:"Enregistrer un bien",
      host_label_title:"Titre de l’hébergement",
      host_label_city:"Ville",
      host_label_type:"Type",
      host_register_btn:"Envoyer l’inscription"
    },
    tr:{
      nav:{home:"Ana sayfa",deals:"Fırsatlar",membership:"Üyelik",host:"Ev Sahibi",support:"Destek"},
      kicker:"Küresel konaklamalar • Doğrulanmış ev sahipleri • Premium tasarım",
      h1:"Lüks konaklamalar.<br><span class='gold'>Küresel erişim.</span>",
      pay:"Kart, havale & kripto (BTC · ETH · USDT).",
      filters:"Filtreler", search:"Ara", popular:"Popüler:", level:"Seviye", plus:"StayWorld+ aktif",
      deals_title:"Sizin için doğrulanmış konaklamalar",
      level_hint:"Puan kazanın. 60+ gün pasif ➝ otomatik düşürme (−1).",
      placeholder:"Paris, Tokyo, İstanbul…",
      auth:{login:"Giriş",signup:"Kaydol"},

      membership_title:"StayWorld+ Ödülleri",
      membership_sub:"Üst seviyeler, alt seviyelerin tüm avantajlarını içerir.",
      level_bronze:"Bronz", bronze_desc:"Kayıtla birlikte temel erişim.",
      level_silver:"Gümüş", silver_desc:"İlk rezervasyonda %3 puan.",
      level_gold:"Altın", gold_desc:"Her rezervasyonda %5 puan + öncelikli destek.",
      level_platinum:"Platin", platinum_desc:"%7 puan + sezon indirimleri.",
      level_diamond:"Elmas", diamond_desc:"%10 puan + özel kuponlar + VIP destek.",
      level_elite:"Elit", elite_desc:"%15 puan + özel fırsatlar + acil öncelikli hizmet.",

      login_title:"StayWorld Giriş", login_sub:"Tekrar hoş geldiniz. Rezervasyon ve puanlarınıza erişin.",
      login_email_label:"E-posta", login_email_ph:"siz@ornek.com",
      login_password_label:"Şifre", login_password_ph:"Şifrenizi girin",
      login_remember:"Beni hatırla", login_forgot:"Şifremi unuttum", login_btn:"Giriş",
      login_to_signup:"Hesabınız yok mu? Kaydolun",

      signup_title:"Hesap oluştur", signup_sub:"İlk günden puan kazanın.",
      signup_name_label:"Ad Soyad", signup_name_ph:"Adınız",
      signup_email_label:"E-posta", signup_email_ph:"siz@ornek.com",
      signup_password_label:"Şifre", signup_password_ph:"En az 8 karakter",
      signup_btn:"Kaydol", signup_to_login:"Zaten hesabınız var mı? Giriş yapın",

      host_title:"Güvenle ev sahipliği yapın", host_sub:"Kimlik doğrulaması gerekir. İlanlar otomatik yayına girer.",
      host_benefits_title:"Avantajlar",
      host_benefit1:"Anında ilan yayını",
      host_benefit2:"Güvenli ödemeler",
      host_benefit3:"YZ tabanlı fiyat önerileri",
      host_benefit4:"7/24 ev sahibi desteği",
      host_verify_btn:"Doğrulamayı başlat",
      host_register_title:"İlan kaydı",
      host_label_title:"İlan başlığı",
      host_label_city:"Şehir",
      host_label_type:"Tür",
      host_register_btn:"Kaydı gönder"
    },
    ja:{
      nav:{home:"ホーム",deals:"お得情報",membership:"メンバーシップ",host:"ホスト",support:"サポート"},
      kicker:"世界の滞在先 • 認証ホスト • プレミアムデザイン",
      h1:"ラグジュアリーな滞在。<br><span class='gold'>グローバルに。</span>",
      pay:"カード・振込・暗号資産 (BTC · ETH · USDT)。",
      filters:"フィルター", search:"検索", popular:"人気:", level:"レベル", plus:"StayWorld+ 有効",
      deals_title:"あなたへの認証済みステイ",
      level_hint:"ポイント獲得。60日以上の非アクティブで自動降格(−1)。",
      placeholder:"パリ、東京、イスタンブール…",
      auth:{login:"ログイン",signup:"登録"},

      membership_title:"StayWorld+ リワード",
      membership_sub:"上位レベルは下位レベルの全特典を含みます。",
      level_bronze:"ブロンズ", bronze_desc:"登録時に基本アクセス付与。",
      level_silver:"シルバー", silver_desc:"初回予約で3%ポイント。",
      level_gold:"ゴールド", gold_desc:"毎回の予約で5%ポイント + 優先サポート。",
      level_platinum:"プラチナ", platinum_desc:"7%ポイント + シーズン割引。",
      level_diamond:"ダイヤモンド", diamond_desc:"10%ポイント + 限定クーポン + VIPサポート。",
      level_elite:"エリート", elite_desc:"15%ポイント + プライベートディール + 緊急優先サービス。",

      login_title:"StayWorld にログイン", login_sub:"お帰りなさい。予約・ポイント・特典へアクセス。",
      login_email_label:"メール", login_email_ph:"あなた@example.com",
      login_password_label:"パスワード", login_password_ph:"パスワードを入力",
      login_remember:"ログイン情報を保持", login_forgot:"パスワードをお忘れですか？", login_btn:"ログイン",
      login_to_signup:"アカウント未作成？ 新規登録",

      signup_title:"アカウント作成", signup_sub:"初日からポイントを獲得。",
      signup_name_label:"氏名", signup_name_ph:"お名前",
      signup_email_label:"メール", signup_email_ph:"あなた@example.com",
      signup_password_label:"パスワード", signup_password_ph:"8文字以上",
      signup_btn:"登録", signup_to_login:"すでにアカウントがありますか？ ログイン",

      host_title:"安心してホスティング", host_sub:"本人確認が必要。掲載は自動で公開。",
      host_benefits_title:"特典",
