[build]
  # 빌드 실패 방지: 굳이 빌드 안 해도 되는 프로젝트면 설치만 하고 끝
  command = "npm ci --omit=dev"
  # 정적 파일이 루트에 있다면 점(.) 사용, 폴더가 있으면 그 폴더로 변경
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin", "node-fetch"]

[build.environment]
  NODE_VERSION = "18"
