[build]
  publish = "."                    # 정적 사이트 루트
  functions = "netlify/functions"  # 서버리스 함수 경로

# API 라우팅 (프론트에선 /api/... 로 호출)
[[redirects]]
  from = "/api/crypto/create-charge"
  to   = "/.netlify/functions/create-charge"
  status = 200

[[redirects]]
  from = "/api/crypto/webhook"
  to   = "/.netlify/functions/crypto-webhook"
  status = 200

# (선택) CORS 헤더
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Requested-With"
    Access-Control-Allow-Methods = "POST, OPTIONS"
