[build]
  command = "npm install"   # ← 여기만 npm install 로 변경
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin", "node-fetch"]

[build.environment]
  NODE_VERSION = "18"
