// /scripts/lang.membership.patch.js
(function(){
  if (!window.LANGS) { console.warn('[i18n] LANGS not found. Load lang.js first.'); return; }

  const M = {
    fr:{membership:{
      title:"Avantages du programme",
      subtitle:"Les niveaux supérieurs incluent tous les avantages des niveaux inférieurs.",
      levels:{bronze:"Bronze",silver:"Argent",gold:"Or",platinum:"Platine",diamond:"Diamant",elite:"Élite"},
      perks:{points_back:"{percent}% de points à chaque réservation"},
      retention_rule:"Sans réservation pendant {days} jours, rétrogradation automatique d’un niveau.",
      progress_title:"Niveau maximal atteint.",
      progress_to_next:"Plus que {amount} pour atteindre {level}.",
      status_current_level:"Votre niveau : {level}",
      member_prices:"Tarifs réservés aux membres",
      basic_support:"Assistance standard",
      secure_pay:"Paiements sécurisés (Cartes & Crypto)",
      free_cancel:"Fenêtre d’annulation gratuite",
      priority_email:"Assistance e-mail prioritaire",
      priority_chat:"Chat prioritaire",
      late_checkout:"Départ tardif (si disponible)",
      upgrade_when_available:"Surclassement (si disponible)",
      b2b_invoice:"Facturation B2B",
      elite_concierge:"Conciergerie Élite",
      defaults:{days:60}
    }},
    ja:{membership:{
      title:"メンバーシップ特典",
      subtitle:"上位ランクは下位ランクの特典をすべて含みます。",
      levels:{bronze:"ブロンズ",silver:"シルバー",gold:"ゴールド",platinum:"プラチナ",diamond:"ダイヤモンド",elite:"エリート"},
      perks:{points_back:"予約ごとに{percent}%ポイント還元"},
      retention_rule:"{days}日間予約がない場合、自動的に1ランク降格します。",
      progress_title:"最上位ランクに到達しました。",
      progress_to_next:"{level}まであと{amount}。",
      status_current_level:"現在のランク：{level}",
      member_prices:"会員限定価格",
      basic_support:"標準サポート",
      secure_pay:"安全な支払い（カード & 暗号資産）",
      free_cancel:"無料キャンセル期間",
      priority_email:"優先メールサポート",
      priority_chat:"優先チャット",
      late_checkout:"レイトチェックアウト（空室時）",
      upgrade_when_available:"お部屋のアップグレード（空室時）",
      b2b_invoice:"B2B 請求書",
      elite_concierge:"エリート・コンシェルジュ",
      defaults:{days:60}
    }},
    de:{membership:{
      title:"Mitgliedschaftsvorteile",
      subtitle:"Höhere Stufen enthalten alle Vorteile der unteren Stufen.",
      levels:{bronze:"Bronze",silver:"Silber",gold:"Gold",platinum:"Platin",diamond:"Diamant",elite:"Elite"},
      perks:{points_back:"{percent}% Punkte pro Buchung"},
      retention_rule:"Ohne Buchung innerhalb von {days} Tagen automatische Herabstufung um eine Stufe.",
      progress_title:"Höchste Stufe erreicht.",
      progress_to_next:"Nur noch {amount} bis {level}.",
      status_current_level:"Dein Level: {level}",
      member_prices:"Mitgliederpreise",
      basic_support:"Standard-Support",
      secure_pay:"Sichere Zahlungen (Karten & Krypto)",
      free_cancel:"Kostenlose Stornofrist",
      priority_email:"Priorisierter E-Mail-Support",
      priority_chat:"Priorisierter Chat",
      late_checkout:"Später Check-out (wenn verfügbar)",
      upgrade_when_available:"Upgrade (wenn verfügbar)",
      b2b_invoice:"B2B-Rechnungen",
      elite_concierge:"Elite-Concierge",
      defaults:{days:60}
    }},
    es:{membership:{
      title:"Beneficios de membresía",
      subtitle:"Los niveles superiores incluyen todas las ventajas de los niveles inferiores.",
      levels:{bronze:"Bronce",silver:"Plata",gold:"Oro",platinum:"Platino",diamond:"Diamante",elite:"Élite"},
      perks:{points_back:"{percent}% de puntos por cada reserva"},
      retention_rule:"Si no hay reservas durante {days} días, se te degradará automáticamente un nivel.",
      progress_title:"Nivel máximo alcanzado.",
      progress_to_next:"Faltan {amount} para llegar a {level}.",
      status_current_level:"Tu nivel: {level}",
      member_prices:"Precios para miembros",
      basic_support:"Soporte estándar",
      secure_pay:"Pagos seguros (Tarjetas y Cripto)",
      free_cancel:"Ventana de cancelación gratuita",
      priority_email:"Soporte por correo prioritario",
      priority_chat:"Chat prioritario",
      late_checkout:"Salida tardía (si hay disponibilidad)",
      upgrade_when_available:"Mejora de habitación (si hay disponibilidad)",
      b2b_invoice:"Factura B2B",
      elite_concierge:"Conserje Élite",
      defaults:{days:60}
    }},
    it:{membership:{
      title:"Vantaggi dell’abbonamento",
      subtitle:"I livelli superiori includono tutti i vantaggi di quelli inferiori.",
      levels:{bronze:"Bronzo",silver:"Argento",gold:"Oro",platinum:"Platino",diamond:"Diamante",elite:"Élite"},
      perks:{points_back:"{percent}% di punti per ogni prenotazione"},
      retention_rule:"Se non effettui prenotazioni per {days} giorni, verrai retrocesso di 1 livello.",
      progress_title:"Raggiunto il livello massimo.",
      progress_to_next:"Mancano {amount} per raggiungere {level}.",
      status_current_level:"Il tuo livello: {level}",
      member_prices:"Prezzi riservati ai membri",
      basic_support:"Assistenza standard",
      secure_pay:"Pagamenti sicuri (Carte & Crypto)",
      free_cancel:"Finestra di cancellazione gratuita",
      priority_email:"Assistenza email prioritaria",
      priority_chat:"Chat prioritaria",
      late_checkout:"Late check-out (se disponibile)",
      upgrade_when_available:"Upgrade camera (se disponibile)",
      b2b_invoice:"Fatturazione B2B",
      elite_concierge:"Concierge Élite",
      defaults:{days:60}
    }},
    tr:{membership:{
      title:"Üyelik Avantajları",
      subtitle:"Üst seviyeler alt seviyelerin tüm ayrıcalıklarını içerir.",
      levels:{bronze:"Bronz",silver:"Gümüş",gold:"Altın",platinum:"Platin",diamond:"Elmas",elite:"Elit"},
      perks:{points_back:"Her rezervasyonda %{percent} puan iadesi"},
      retention_rule:"{days} gün boyunca rezervasyon yoksa seviyen otomatik olarak bir kademe düşürülür.",
      progress_title:"En üst seviye ulaşıldı.",
      progress_to_next:"{level} seviyesine ulaşmak için {amount} kaldı.",
      status_current_level:"Seviyen: {level}",
      member_prices:"Üyelere özel fiyatlar",
      basic_support:"Standart destek",
      secure_pay:"Güvenli ödemeler (Kart & Kripto)",
      free_cancel:"Ücretsiz iptal süresi",
      priority_email:"Öncelikli e-posta desteği",
      priority_chat:"Öncelikli sohbet",
      late_checkout:"Geç çıkış (müsaitse)",
      upgrade_when_available:"Oda yükseltme (müsaitse)",
      b2b_invoice:"B2B faturalandırma",
      elite_concierge:"Elit konsiyerj",
      defaults:{days:60}
    }},
    zh:{membership:{
      title:"会员权益",
      subtitle:"更高级别包含所有低级别的权益。",
      levels:{bronze:"青铜",silver:"白银",gold:"黄金",platinum:"铂金",diamond:"钻石",elite:"精英"},
      perks:{points_back:"每次预订返还 {percent}% 积分"},
      retention_rule:"若 {days} 天内无预订，将自动降级一级。",
      progress_title:"已达到最高等级。",
      progress_to_next:"距离 {level} 还差 {amount}。",
      status_current_level:"你的等级：{level}",
      member_prices:"会员专属价格",
      basic_support:"标准支持",
      secure_pay:"安全支付（银行卡 & 加密货币）",
      free_cancel:"免费取消时段",
      priority_email:"优先邮件支持",
      priority_chat:"优先在线客服",
      late_checkout:"延迟退房（视房态）",
      upgrade_when_available:"客房升级（视房态）",
      b2b_invoice:"B2B 发票",
      elite_concierge:"精英礼宾服务",
      defaults:{days:60}
    }},
    ru:{membership:{
      title:"Преимущества членства",
      subtitle:"Более высокий уровень включает все преимущества нижних уровней.",
      levels:{bronze:"Бронза",silver:"Серебро",gold:"Золото",platinum:"Платина",diamond:"Бриллиант",elite:"Элита"},
      perks:{points_back:"{percent}% бонусов за каждое бронирование"},
      retention_rule:"Если нет бронирований в течение {days} дней, произойдет автоматическое понижение на один уровень.",
      progress_title:"Достигнут максимальный уровень.",
      progress_to_next:"Осталось {amount} до уровня {level}.",
      status_current_level:"Ваш уровень: {level}",
      member_prices:"Цены только для участников",
      basic_support:"Стандартная поддержка",
      secure_pay:"Безопасные платежи (Карты и Крипто)",
      free_cancel:"Период бесплатной отмены",
      priority_email:"Приоритетная поддержка по email",
      priority_chat:"Приоритетный чат",
      late_checkout:"Поздний выезд (при наличии)",
      upgrade_when_available:"Апгрейд номера (при наличии)",
      b2b_invoice:"B2B-счета",
      elite_concierge:"Элит-консьерж",
      defaults:{days:60}
    }}
  };

  Object.keys(M).forEach(code=>{
    window.LANGS[code] = window.LANGS[code] || {};
    window.LANGS[code].membership = { ...(window.LANGS[code].membership||{}), ...M[code].membership };
  });

  console.log('[i18n] membership patch merged for:', Object.keys(M).join(', '));
})();
